[package]
name = "am-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
am-core = { path = "../am-core" }
am-crypto = { path = "../am-crypto" }
anyhow.workspace = true
image.workspace = true
rand.workspace = true
sha2.workspace = true
rusqlite = { workspace = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
image.workspace = true
tempfile = "3"
